# SPDX-FileCopyrightText: 2020 inovex GmbH <https://www.inovex.de>
# 
# SPDX-License-Identifier: MIT
variable "base_name" {
  type        = string
  description = "A prefix which will be attached to all resources generated by this module"
}

variable "lambda_path" {
  type        = string
  description = "Path for lambda.zip"
}

variable "env" {
  type        = map(string)
  description = "Environment variables of lambda"
}
